In [5]:
from scipy.io import loadmat

In [28]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\shaya\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [29]:
annots = loadmat('E:\Dropbox (Technion Dropbox)\Test\SM04\08_18_19_tuft_Final_Version\Analysis\Structural_VS_FunctionalAnalysis\cluster3pks10\GraphAsMatrix.mat')

ValueError: embedded null character

In [7]:
print(annots)

NameError: name 'annots' is not defined

In [ ]:
locals()


In [ ]:
gloubls()


In [1]:
%who

Interactive namespace is empty.


In [2]:
f = 5

In [3]:
4+4


8

In [8]:
annots = loadmat('E:\Dropbox (Technion Dropbox)\Test\SM04\08_18_19_tuft_Final_Version\Analysis\Structural_VS_FunctionalAnalysis\cluster3pks10\GraphAsMatrix.mat')

ValueError: embedded null character

In [17]:
annots = loadmat('GraphAsMatrix.mat')

In [30]:
saveValues = annots.get('matrixForHS')

In [41]:
print(saveValues)


[[1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]


In [10]:
import numpy as np

In [11]:
import h5py

ModuleNotFoundError: No module named 'h5py'

In [12]:
pip install h5py

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\shaya\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [13]:
import h5py


In [15]:
f = h5py.File('GraphAsMatrix.mat','r')

OSError: Unable to open file (file signature not found)